import os
import uuid
from git import Repo
from github import Github
from app.config import GITHUB_TOKEN, GITHUB_REPO_URL, GITHUB_BASE_BRANCH, GITHUB_LOCAL_PATH
from typing import Dict, Set

client = Github(GITHUB_TOKEN, verify=False)

def load_github_repo():
    global repo
    if not os.path.exists(GITHUB_LOCAL_PATH):
        repo = Repo.clone_from(GITHUB_REPO_URL, GITHUB_LOCAL_PATH)
    else:
        repo = Repo(GITHUB_LOCAL_PATH)

def apply_changes_and_raise_pr(exception: str):
    print("apply changes")
    branch = f"llm-fix/{uuid.uuid4().hex[:8]}"

    
# --- SAFETY: ensure clean working tree ---
    #repo.git.fetch("origin")

    repo.git.checkout(GITHUB_BASE_BRANCH)
    repo.git.pull("origin", GITHUB_BASE_BRANCH)
    
    #repo.git.reset("--hard", f"origin/{GITHUB_BASE_BRANCH}")
    #repo.git.clean("-fd")  # remove untracked files/directories

    repo.git.checkout("-b", branch)

    # Git produces authoritative diff
    diff = repo.git.diff()
    if not diff.strip():
        print("⚠ No changes detected.")
        return

    repo.git.add(A=True)
    repo.index.commit(f"Fix: {exception}")
    repo.remote().push(branch)

    repo_full_name = get_github_repo_full_name(GITHUB_REPO_URL)

    gh_repo = client.get_repo(repo_full_name)


    pr = gh_repo.create_pull(
        title=f"Fix: {exception}",
        body="Auto-generated by LLM log monitor",
        head=branch,
        base=GITHUB_BASE_BRANCH,
    )

    print("✅ PR created:", pr.html_url)

def get_github_repo_full_name(repo_url: str) -> str:
    """
    Converts:
    https://github.com/owner/repo.git
    → owner/repo
    """
    if repo_url.endswith(".git"):
        repo_url = repo_url[:-4]

    return repo_url.replace("https://github.com/", "")    

def find_java_files_in_repo(root: str, java_files: Set[str]) -> Dict[str, str]:
    print("finding files from repo")
    files = {}

    for dirpath, _, filenames in os.walk(root):
        for f in filenames:
            if f in java_files:
                full = os.path.join(dirpath, f)
                rel = os.path.relpath(full, root)
                with open(full, "r", encoding="utf-8", errors="ignore") as fh:
                    files[rel] = fh.read()

    return files    